export const PRODUCTS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  FILTER_BY_CATEGORY: 'FILTER_BY_CATEGORY'
};

export const CATEGORIES = {
  GET_CATEGORIES: 'GET_CATEGORIES'
};

export const CART = {
  ADD_TO_CART: 'ADD_TO_CART',
  CLEAR_CART: 'CLEAR_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY'
};

export const TIMER = {
  START_TIMER: 'START_TIMER',
  DECREASE_TIMER: 'DECREASE_TIMER',
  END_TIMER: 'END_TIMER'
};

export default {
  PRODUCTS,
  CATEGORIES,
  CART,
  TIMER
};
